[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/ch1"
  to = "/ch1.html"
  status = 200

[[redirects]]
  from = "/ch1-admin"
  to = "/ch1-admin.html"
  status = 200

[[redirects]]
  from = "/admin-login"
  to = "/admin-login.html"
  status = 200
