/* auto-generated by rebuild-tmhi-ucla.js – do not edit */
(function () {
  'use strict';

  var React = window.React;
  var Recharts = window.Recharts;
  var useState = React.useState,
    useMemo = React.useMemo,
    useEffect = React.useEffect,
    useRef = React.useRef,
    Fragment = React.Fragment;
  var BarChart = Recharts.BarChart,
    Bar = Recharts.Bar,
    XAxis = Recharts.XAxis,
    YAxis = Recharts.YAxis,
    CartesianGrid = Recharts.CartesianGrid,
    Tooltip = Recharts.Tooltip,
    ResponsiveContainer = Recharts.ResponsiveContainer,
    RadarChart = Recharts.RadarChart,
    Radar = Recharts.Radar,
    PolarGrid = Recharts.PolarGrid,
    PolarAngleAxis = Recharts.PolarAngleAxis,
    PolarRadiusAxis = Recharts.PolarRadiusAxis,
    LineChart = Recharts.LineChart,
    Line = Recharts.Line,
    AreaChart = Recharts.AreaChart,
    Area = Recharts.Area,
    PieChart = Recharts.PieChart,
    Pie = Recharts.Pie,
    Cell = Recharts.Cell,
    ScatterChart = Recharts.ScatterChart,
    Scatter = Recharts.Scatter,
    ZAxis = Recharts.ZAxis,
    ComposedChart = Recharts.ComposedChart,
    Legend = Recharts.Legend,
    ReferenceLine = Recharts.ReferenceLine;

  // ─── TMHI-15 Structure ────────────────────────────────────────────────────────
  // 15 ข้อ · ข้อละ 1-4 คะแนน · เต็ม 60
  // ข้อ 1-3, 7-15 ปกติ | ข้อ 4-6 Reverse (4→1, 3→2, 2→3, 1→4)
  // ยิ่งสูง = สุขภาพจิตดี
  // เกณฑ์กรมสุขภาพจิต 2550:
  //   51-60 = ดีกว่าคนทั่วไป
  //   44-50 = เท่ากับคนทั่วไป
  //   ≤ 43  = ต่ำกว่าคนทั่วไป

  const LEVEL_CFG = [{
    key: "high",
    label: "ดีกว่าคนทั่วไป",
    range: "51–60",
    color: "#10B981",
    bg: "#F0FDF4",
    min: 51,
    max: 60
  }, {
    key: "mid",
    label: "เท่ากับคนทั่วไป",
    range: "44–50",
    color: "#F59E0B",
    bg: "#FFFBEB",
    min: 44,
    max: 50
  }, {
    key: "low",
    label: "ต่ำกว่าคนทั่วไป",
    range: "≤ 43",
    color: "#EF4444",
    bg: "#FEF2F2",
    min: 0,
    max: 43
  }];
  const getLevel = score => {
    if (score >= 51) return LEVEL_CFG[0];
    if (score >= 44) return LEVEL_CFG[1];
    return LEVEL_CFG[2];
  };

  // 5 มิติเสริม (จัดกลุ่มตามเนื้อหา ไม่ใช่ sub-scale มาตรฐาน)
  const DIMS = [{
    key: "happiness",
    label: "ความสุขในชีวิต",
    short: "ความสุข",
    icon: "😊",
    items: [0, 1, 2],
    // 0-based index ใน 15 ข้อ
    color: "#F59E0B",
    desc: "ข้อ 1-3 · พึงพอใจ สบายใจ ภูมิใจในตนเอง"
  }, {
    key: "stress",
    label: "ความยืดหยุ่นทางใจ",
    short: "ยืดหยุ่น",
    icon: "💪",
    items: [3, 4, 5],
    // ข้อ 4-6 (Reverse แล้ว)
    color: "#6366F1",
    desc: "ข้อ 4-6 (Reverse) · ไม่เบื่อหน่าย ไม่ผิดหวัง ไม่รู้สึกทุกข์"
  }, {
    key: "selfmgmt",
    label: "การจัดการตนเอง",
    short: "จัดการ",
    icon: "🎯",
    items: [6, 7, 8],
    color: "#10B981",
    desc: "ข้อ 7-9 · ยอมรับปัญหา ควบคุมอารมณ์ เผชิญเหตุร้าย"
  }, {
    key: "empathy",
    label: "การเห็นอกเห็นใจ",
    short: "เห็นใจ",
    icon: "🤝",
    items: [9, 10, 11],
    color: "#EC4899",
    desc: "ข้อ 10-12 · เห็นอกเห็นใจ สุขในการช่วยเหลือ ให้ความช่วยเหลือ"
  }, {
    key: "family",
    label: "ความมั่นคงครอบครัว",
    short: "ครอบครัว",
    icon: "🏠",
    items: [12, 13, 14],
    color: "#14B8A6",
    desc: "ข้อ 13-15 · มั่นคงปลอดภัย ครอบครัวดูแล ผูกพันกัน"
  }];
  const ITEM_LABELS = ["ท่านรู้สึกพึงพอใจในชีวิต", "ท่านรู้สึกสบายใจ", "ท่านรู้สึกภูมิใจในตนเอง", "ท่านรู้สึกเบื่อหน่ายท้อแท้กับการดำเนินชีวิตประจำวัน", "ท่านรู้สึกผิดหวังในตนเอง", "ท่านรู้สึกว่าชีวิตมีแต่ความทุกข์", "ท่านสามารถทำใจยอมรับได้สำหรับปัญหาที่ยากจะแก้ไข (เมื่อมีปัญหา)", "ท่านมั่นใจว่าจะสามารถควบคุมอารมณ์ได้เมื่อมีเหตุการณ์คับขัน", "ท่านมั่นใจที่จะเผชิญกับเหตุการณ์ร้ายแรงที่เกิดขึ้นในชีวิต", "ท่านรู้สึกเห็นอกเห็นใจเมื่อผู้อื่นมีความทุกข์", "ท่านรู้สึกเป็นสุขในการช่วยเหลือผู้อื่นที่มีปัญหา", "ท่านให้ความช่วยเหลือแก่ผู้อื่นเมื่อมีโอกาส", "ท่านรู้สึกมั่นคงปลอดภัยเมื่ออยู่ในครอบครัว", "หากท่านป่วยหนัก ท่านเชื่อว่าคนในครอบครัวจะดูแลท่านเป็นอย่างดี", "สมาชิกในครอบครัวมีความรักและผูกพันต่อกัน"];

  // IDP suggestion per item
  const IDP_MAP = ["กิจกรรม Gratitude Journal / สำรวจสิ่งดีในชีวิตประจำวัน", "Mindfulness 10 นาที/วัน / กิจกรรมลดความเครียด", "Coaching เสริมสร้างความภาคภูมิใจ / บันทึกความสำเร็จ", "โปรแกรมจัดการความเครียด / เทคนิคผ่อนคลาย", "พบนักจิตวิทยา / ปรับมุมมองต่อตนเอง (Reframing)", "กลุ่ม Peer Support / พูดคุยกับผู้เชี่ยวชาญ EAP", "ฝึกทักษะการยอมรับ (Acceptance) / Resilience Training", "Workshop จัดการอารมณ์ / EQ Training", "โปรแกรม Resilience / กิจกรรมสร้างความแข็งแกร่งทางใจ", "กิจกรรมอาสาสมัคร / งานจิตอาสาในองค์กร", "สร้างโอกาสช่วยเหลือเพื่อนร่วมงาน / Mentor Program", "ส่งเสริมวัฒนธรรมการช่วยเหลือในทีม", "กิจกรรม Work-Life Balance / ลดชั่วโมงทำงาน", "บริการปรึกษาครอบครัว / EAP Program", "กิจกรรมสร้างสัมพันธ์ครอบครัว / Family Day"];

  // ─── Heatmap helpers ──────────────────────────────────────────────────────────
  // TMHI raw response: 0-3 (stored as tmhi_1…tmhi_15 in cleaned_data)
  // Displayed labels: ไม่เลย(0) เล็กน้อย(1) มาก(2) มากที่สุด(3)
  const TMHI_LEVELS = ["ไม่เลย", "เล็กน้อย", "มาก", "มากที่สุด"];
  const TMHI_REVERSE_IDX = new Set([3, 4, 5]); // 0-based index 3,4,5 = ข้อ 4,5,6

  function buildTmhiHeatmapData(empArray) {
    // empArray: each emp has rawAnswers (0-based 15 items, raw 1-4) OR _raw row with tmhi_1…tmhi_15
    const counts = Array.from({
      length: 15
    }, () => [0, 0, 0, 0]); // [level0..3]
    let n = 0;
    empArray.forEach(emp => {
      let raw15 = null;
      if (emp._raw) {
        // real data: tmhi_1..tmhi_15 are 0-3
        raw15 = Array.from({
          length: 15
        }, (_, i) => {
          const v = Number(emp._raw[`tmhi_${i + 1}`]);
          return Number.isFinite(v) && v >= 0 && v <= 3 ? v : null;
        });
      } else if (emp.rawAnswers) {
        // mock data: rawAnswers are 1-4 → convert to 0-3
        raw15 = emp.rawAnswers.map(v => v - 1);
      }
      if (!raw15 || raw15.some(v => v == null)) return;
      n++;
      raw15.forEach((v, i) => {
        counts[i][v]++;
      });
    });
    return {
      counts,
      n
    };
  }
  function computeTmhiHeatmapRows(empArray) {
    const {
      counts,
      n
    } = buildTmhiHeatmapData(empArray);
    if (n === 0) return null;
    return ITEM_LABELS.map((label, i) => {
      const row = counts[i];
      const total = row.reduce((s, c) => s + c, 0) || 1;
      return {
        idx: i,
        label,
        isReverse: TMHI_REVERSE_IDX.has(i),
        pcts: row.map(c => Math.round(c / total * 100)),
        counts: row,
        n: total
      };
    });
  }

  // 4-level cell background using selected base color
  const HEAT_PRESETS = [{
    name: "น้ำเงิน",
    hex: "#3B5FA0"
  }, {
    name: "เขียว",
    hex: "#0F8A6A"
  }, {
    name: "ม่วง",
    hex: "#6D28D9"
  }, {
    name: "แดง",
    hex: "#C0392B"
  }, {
    name: "ส้ม",
    hex: "#D97706"
  }];
  function hexToRgb(hex) {
    const r = parseInt(hex.slice(1, 3), 16),
      g = parseInt(hex.slice(3, 5), 16),
      b = parseInt(hex.slice(5, 7), 16);
    return [r, g, b];
  }
  function heatCellBg(pct, colorHex) {
    if (pct < 25) return "transparent";
    const [r, g, b] = hexToRgb(colorHex);
    const alpha = pct < 50 ? 0.20 : pct < 75 ? 0.48 : 0.80;
    return `rgba(${r},${g},${b},${alpha})`;
  }
  const HeatmapTableTMHI = ({
    empArray
  }) => {
    const [mode, setMode] = useState("pct");
    const [colorHex, setColorHex] = useState(HEAT_PRESETS[0].hex);
    const tableRef = useRef(null);
    const rows = useMemo(() => computeTmhiHeatmapRows(empArray || []), [empArray]);
    const handleDownload = () => {
      const node = tableRef.current;
      if (!node) return;
      // Use html-to-image via canvas approach with dom serialization
      const scale = 2;
      const w = node.offsetWidth,
        h = node.offsetHeight;
      const canvas = document.createElement("canvas");
      canvas.width = w * scale;
      canvas.height = h * scale;
      const ctx = canvas.getContext("2d");
      ctx.scale(scale, scale);
      ctx.fillStyle = "#fff";
      ctx.fillRect(0, 0, w, h);
      const xml = new XMLSerializer().serializeToString(node);
      const svgStr = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml">${xml}</div></foreignObject></svg>`;
      const img = new Image();
      img.onload = () => {
        ctx.drawImage(img, 0, 0);
        const a = document.createElement("a");
        a.download = "heatmap-tmhi.png";
        a.href = canvas.toDataURL("image/png");
        a.click();
      };
      img.src = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(svgStr);
    };
    if (!rows) return /*#__PURE__*/React.createElement("div", {
      style: {
        padding: 40,
        textAlign: "center",
        color: "#9CA3AF",
        fontSize: 13
      }
    }, "\u0E44\u0E21\u0E48\u0E21\u0E35\u0E02\u0E49\u0E2D\u0E21\u0E39\u0E25 TMHI \u0E23\u0E32\u0E22\u0E02\u0E49\u0E2D");
    const colW = ["42%", "14.5%", "14.5%", "14.5%", "14.5%"];
    const headerStyle = {
      fontSize: 11,
      fontWeight: 700,
      color: "#6B7280",
      padding: "8px 6px",
      textAlign: "center",
      borderBottom: "2px solid #E5E7EB",
      whiteSpace: "nowrap"
    };
    const [r, g, b] = hexToRgb(colorHex);
    return /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 12,
        flexWrap: "wrap",
        gap: 8
      }
    }, /*#__PURE__*/React.createElement("span", {
      style: {
        fontSize: 14,
        fontWeight: 800,
        color: "#92400E"
      }
    }, "\uD83D\uDD25 Heatmap \u0E23\u0E32\u0E22\u0E02\u0E49\u0E2D \u2014 \u0E19\u0E49\u0E33\u0E2B\u0E19\u0E31\u0E01\u0E04\u0E33\u0E15\u0E2D\u0E1A\u0E02\u0E2D\u0E07\u0E1C\u0E39\u0E49\u0E15\u0E2D\u0E1A"), /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        gap: 6,
        alignItems: "center",
        flexWrap: "wrap"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        gap: 5,
        alignItems: "center",
        background: "#F9FAFB",
        borderRadius: 8,
        padding: "4px 8px"
      }
    }, HEAT_PRESETS.map(p => /*#__PURE__*/React.createElement("button", {
      key: p.hex,
      title: p.name,
      onClick: () => setColorHex(p.hex),
      style: {
        width: 22,
        height: 22,
        borderRadius: "50%",
        background: p.hex,
        border: colorHex === p.hex ? "2.5px solid #111" : "2px solid transparent",
        cursor: "pointer",
        padding: 0,
        outline: "none",
        transition: "border 0.15s"
      }
    }))), [["pct", "%"], ["count", "คน"]].map(([k, l]) => /*#__PURE__*/React.createElement("button", {
      key: k,
      onClick: () => setMode(k),
      style: {
        padding: "4px 14px",
        borderRadius: 6,
        fontSize: 12,
        fontWeight: 700,
        border: "none",
        cursor: "pointer",
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif",
        background: mode === k ? "#92400E" : "#F3F4F6",
        color: mode === k ? "#fff" : "#6B7280"
      }
    }, l)), /*#__PURE__*/React.createElement("button", {
      onClick: handleDownload,
      style: {
        padding: "4px 14px",
        borderRadius: 6,
        fontSize: 12,
        fontWeight: 700,
        border: "none",
        cursor: "pointer",
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif",
        background: "#1E40AF",
        color: "#fff",
        display: "flex",
        alignItems: "center",
        gap: 5
      }
    }, "\u2B07 \u0E1A\u0E31\u0E19\u0E17\u0E36\u0E01\u0E23\u0E39\u0E1B"))), /*#__PURE__*/React.createElement("div", {
      ref: tableRef,
      style: {
        overflowX: "auto",
        background: "#fff",
        padding: 4
      }
    }, /*#__PURE__*/React.createElement("table", {
      style: {
        width: "100%",
        borderCollapse: "collapse",
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif"
      }
    }, /*#__PURE__*/React.createElement("colgroup", null, colW.map((w, i) => /*#__PURE__*/React.createElement("col", {
      key: i,
      style: {
        width: w
      }
    }))), /*#__PURE__*/React.createElement("thead", null, /*#__PURE__*/React.createElement("tr", {
      style: {
        background: "#F9FAFB"
      }
    }, /*#__PURE__*/React.createElement("th", {
      style: {
        ...headerStyle,
        textAlign: "left",
        paddingLeft: 10
      }
    }, "\u0E02\u0E49\u0E2D / \u0E23\u0E30\u0E14\u0E31\u0E1A"), TMHI_LEVELS.map((l, i) => /*#__PURE__*/React.createElement("th", {
      key: i,
      style: headerStyle
    }, l)))), /*#__PURE__*/React.createElement("tbody", null, rows.map((row, ri) => /*#__PURE__*/React.createElement("tr", {
      key: ri,
      style: {
        borderBottom: "1px solid #F3F4F6",
        background: ri % 2 === 0 ? "#fff" : "#FAFAFA"
      }
    }, /*#__PURE__*/React.createElement("td", {
      style: {
        padding: "9px 10px",
        fontSize: 12,
        color: "#374151",
        verticalAlign: "middle",
        lineHeight: 1.45
      }
    }, /*#__PURE__*/React.createElement("span", {
      style: {
        color: "#9CA3AF",
        marginRight: 6,
        fontSize: 11,
        fontWeight: 700
      }
    }, ri + 1, "."), row.label, row.isReverse && /*#__PURE__*/React.createElement("span", {
      style: {
        marginLeft: 6,
        fontSize: 10,
        color: "#6366F1",
        background: "#EEF2FF",
        borderRadius: 4,
        padding: "1px 5px"
      }
    }, "\u0E22\u0E49\u0E2D\u0E19\u0E01\u0E25\u0E31\u0E1A")), row.pcts.map((pct, li) => {
      const bg = heatCellBg(pct, colorHex);
      const val = mode === "pct" ? `${pct}%` : row.counts[li].toLocaleString();
      const dark = pct >= 75;
      return /*#__PURE__*/React.createElement("td", {
        key: li,
        style: {
          padding: "8px 6px",
          textAlign: "center",
          verticalAlign: "middle",
          background: bg,
          fontWeight: pct >= 50 ? 700 : 400,
          fontSize: 12,
          color: dark ? "#fff" : pct >= 25 ? "#1E293B" : "#9CA3AF",
          transition: "background 0.2s"
        }
      }, val);
    })))))), /*#__PURE__*/React.createElement("div", {
      style: {
        marginTop: 10,
        fontSize: 10,
        color: "#9CA3AF",
        display: "flex",
        gap: 12,
        flexWrap: "wrap",
        alignItems: "center"
      }
    }, [["< 25%", 0.0], ["25–50%", 0.20], ["50–75%", 0.48], ["75%+", 0.80]].map(([lbl, a]) => /*#__PURE__*/React.createElement("span", {
      key: lbl,
      style: {
        display: "flex",
        alignItems: "center",
        gap: 4
      }
    }, /*#__PURE__*/React.createElement("span", {
      style: {
        display: "inline-block",
        width: 12,
        height: 12,
        borderRadius: 2,
        background: a === 0 ? "#E5E7EB" : `rgba(${r},${g},${b},${a})`,
        border: "1px solid #E5E7EB"
      }
    }), lbl)), /*#__PURE__*/React.createElement("span", {
      style: {
        marginLeft: "auto"
      }
    }, "\u0E21\u0E35\u0E02\u0E49\u0E2D\u0E21\u0E39\u0E25 ", rows[0]?.n?.toLocaleString() || 0, " \u0E04\u0E19")));
  };

  // ─── Mock Data ────────────────────────────────────────────────────────────────
  const rand = (a, b) => Math.floor(Math.random() * (b - a + 1)) + a;
  const NAMES = ["นายสมชาย ใจดี", "นางสาวมาลี รักสุข", "นายประสิทธิ์ ทำงาน", "นางวิภา สดใส", "นายกิตติ เก่งมาก", "นางสาวอัญชลี ร่าเริง", "นายวีระ ขยันดี", "นางรัตนา มีสุข", "นายพิทักษ์ ตั้งใจ", "นางสาวสุภา สวยงาม", "นายอนุชา ดีเลิศ", "นางเพ็ญศรี แจ่มใส", "นายชัยวัฒน์ รุ่งเรือง", "นางสาวนิภา ยิ้มแย้ม", "นายสุรศักดิ์ มั่นคง", "นางกัลยา ใสสะอาด", "นายธนพล ฉลาดดี", "นางสาวลัดดา สะอาด", "นายปิยะ เฉลียวฉลาด", "นางวรรณา สุขสบาย"];
  const DEPTS = ["นโยบาย", "ปฏิบัติการ", "สนับสนุน"];
  const genEmployee = (name, idx) => {
    const tier = idx < 5 ? [1, 3] : idx < 13 ? [2, 4] : [3, 4];
    // raw answers 1-4 per item
    const rawAnswers = Array.from({
      length: 15
    }, () => rand(tier[0], tier[1]));
    // scored: ข้อ 4-6 (index 3,4,5) reverse = 5 - raw
    const scored = rawAnswers.map((v, i) => i >= 3 && i <= 5 ? 5 - v : v);
    const total = scored.reduce((s, v) => s + v, 0);
    const dimScores = DIMS.map(d => {
      const raw = d.items.reduce((s, i) => s + scored[i], 0);
      return {
        key: d.key,
        raw,
        pct: Math.round(raw / (d.items.length * 4) * 100)
      };
    });
    return {
      id: idx + 1,
      name,
      dept: DEPTS[idx % 3],
      rawAnswers,
      scored,
      total,
      level: getLevel(total),
      dimScores,
      totalPct: Math.round(total / 60 * 100)
    };
  };
  const employees = NAMES.map((n, i) => genEmployee(n, i));

  // ─── Aggregates ───────────────────────────────────────────────────────────────
  const avgDim = key => Math.round(employees.reduce((s, e) => s + e.dimScores.find(d => d.key === key).pct, 0) / employees.length);
  const orgAvg = Math.round(employees.reduce((s, e) => s + e.total, 0) / employees.length);
  const orgRadar = DIMS.map(d => ({
    dim: d.icon + " " + d.short,
    fullLabel: d.label,
    "ต่ำกว่าคนทั่วไป (≤43)": Math.round(employees.filter(e => e.level.key === "low").reduce((s, e) => s + e.dimScores.find(x => x.key === d.key).pct, 0) / Math.max(employees.filter(e => e.level.key === "low").length, 1)),
    "ค่าเฉลี่ยองค์กร": avgDim(d.key)
  }));
  const deptData = DEPTS.map(dept => {
    const grp = employees.filter(e => e.dept === dept);
    return {
      name: dept,
      "ดีกว่าคนทั่วไป": grp.filter(e => e.level.key === "high").length,
      "เท่ากับคนทั่วไป": grp.filter(e => e.level.key === "mid").length,
      "ต่ำกว่าคนทั่วไป": grp.filter(e => e.level.key === "low").length
    };
  });

  // ─── Sub-components ───────────────────────────────────────────────────────────
  const Tag = ({
    label,
    color,
    small
  }) => /*#__PURE__*/React.createElement("span", {
    style: {
      background: color + "22",
      color,
      border: `1px solid ${color}44`,
      padding: small ? "1px 8px" : "3px 12px",
      borderRadius: 999,
      fontSize: small ? 10 : 12,
      fontWeight: 700,
      fontFamily: "'IBM Plex Sans Thai Looped',sans-serif"
    }
  }, label);
  const MiniBar = ({
    pct,
    color
  }) => /*#__PURE__*/React.createElement("div", {
    style: {
      height: 5,
      background: "#E5E7EB",
      borderRadius: 3,
      overflow: "hidden",
      flex: 1
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      width: `${pct}%`,
      height: "100%",
      background: color,
      borderRadius: 3
    }
  }));

  // Gauge - ยิ่งสูงยิ่งดี (สีกลับจาก UCLA)
  const Gauge = ({
    score,
    size = 200
  }) => {
    const pctVal = score / 60;
    const startAngle = -210,
      totalDeg = 240;
    const needleDeg = startAngle + pctVal * totalDeg;
    const cx = size / 2,
      cy = size * 0.58,
      r = size * 0.38;
    const toXY = (deg, rad) => ({
      x: cx + rad * Math.cos(deg * Math.PI / 180),
      y: cy + rad * Math.sin(deg * Math.PI / 180)
    });
    const arc = (s, e, ro, ri) => {
      const sp = toXY(s, ro),
        ep = toXY(e, ro);
      const si = toXY(s, ri),
        ei = toXY(e, ri);
      const lg = Math.abs(e - s) > 180 ? 1 : 0;
      return `M${sp.x} ${sp.y} A${ro} ${ro} 0 ${lg} 1 ${ep.x} ${ep.y} L${ei.x} ${ei.y} A${ri} ${ri} 0 ${lg} 0 ${si.x} ${si.y}Z`;
    };
    // ยิ่งสูงยิ่งดี → แดงซ้าย เขียวขวา
    const zones = [{
      s: -210,
      e: -210 + totalDeg * (43 / 60),
      color: "#FCA5A5"
    }, {
      s: -210 + totalDeg * (43 / 60),
      e: -210 + totalDeg * (50 / 60),
      color: "#FCD34D"
    }, {
      s: -210 + totalDeg * (50 / 60),
      e: 30,
      color: "#6EE7B7"
    }];
    const needle = toXY(needleDeg, r * 0.82);
    const lvl = getLevel(score);
    return /*#__PURE__*/React.createElement("svg", {
      width: size,
      height: size * 0.72,
      viewBox: `0 0 ${size} ${size * 0.72}`
    }, zones.map((z, i) => /*#__PURE__*/React.createElement("path", {
      key: i,
      d: arc(z.s, z.e, r, r * 0.6),
      fill: z.color,
      opacity: 0.85
    })), [0, 15, 30, 45, 60].map(v => {
      const deg = startAngle + v / 60 * totalDeg;
      const o = toXY(deg, r + 4),
        inn = toXY(deg, r - 2),
        lbl = toXY(deg, r + 14);
      return /*#__PURE__*/React.createElement("g", {
        key: v
      }, /*#__PURE__*/React.createElement("line", {
        x1: inn.x,
        y1: inn.y,
        x2: o.x,
        y2: o.y,
        stroke: "#64748B",
        strokeWidth: 1.5
      }), /*#__PURE__*/React.createElement("text", {
        x: lbl.x,
        y: lbl.y,
        textAnchor: "middle",
        dominantBaseline: "middle",
        fontSize: size * 0.055,
        fill: "#94A3B8",
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif"
      }, v));
    }), /*#__PURE__*/React.createElement("line", {
      x1: cx,
      y1: cy,
      x2: needle.x,
      y2: needle.y,
      stroke: "#1E293B",
      strokeWidth: 2.5,
      strokeLinecap: "round"
    }), /*#__PURE__*/React.createElement("circle", {
      cx: cx,
      cy: cy,
      r: size * 0.04,
      fill: "#1E293B"
    }), /*#__PURE__*/React.createElement("circle", {
      cx: cx,
      cy: cy,
      r: size * 0.024,
      fill: "#F8FAFC"
    }), /*#__PURE__*/React.createElement("text", {
      x: cx,
      y: cy + size * 0.1,
      textAnchor: "middle",
      fontSize: size * 0.13,
      fontWeight: "800",
      fill: lvl.color,
      fontFamily: "'IBM Plex Sans Thai Looped',sans-serif"
    }, score), /*#__PURE__*/React.createElement("text", {
      x: cx,
      y: cy + size * 0.21,
      textAnchor: "middle",
      fontSize: size * 0.06,
      fill: "#64748B",
      fontFamily: "'IBM Plex Sans Thai Looped',sans-serif"
    }, "/ 60"));
  };
  const CustomTooltip = ({
    active,
    payload,
    label
  }) => {
    if (!active || !payload?.length) return null;
    return /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#1E293B",
        borderRadius: 10,
        padding: "12px 16px",
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        color: "#94A3B8",
        fontSize: 11,
        marginBottom: 8
      }
    }, label), payload.map((p, i) => /*#__PURE__*/React.createElement("div", {
      key: i,
      style: {
        display: "flex",
        gap: 10,
        marginBottom: 4,
        alignItems: "center"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        width: 8,
        height: 8,
        borderRadius: "50%",
        background: p.fill
      }
    }), /*#__PURE__*/React.createElement("span", {
      style: {
        fontSize: 12,
        color: "#E2E8F0"
      }
    }, p.name, ":"), /*#__PURE__*/React.createElement("span", {
      style: {
        fontSize: 12,
        fontWeight: 700,
        color: "#fff"
      }
    }, p.value, " \u0E04\u0E19"))));
  };

  // ─── Main ────────────────────────────────────────────────────────────────────
  function TMHIDashboard() {
    const [tab, setTab] = useState("overview");
    const [filter, setFilter] = useState("all");
    const [selectedEmp, setSelectedEmp] = useState(null);

    // Use real data if available, else mock
    const realBundle = window.__IDP_EMPLOYEES__;
    const allEmps = useMemo(() => {
      if (realBundle && realBundle.tmhi && realBundle.tmhi.length > 0) {
        return realBundle.tmhi.filter(e => e.tmhiScore != null).map(e => {
          const score = e.tmhiScore;
          const lvl = score >= 51 ? LEVEL_CFG[0] : score >= 44 ? LEVEL_CFG[1] : LEVEL_CFG[2];
          // Compute dimScores from raw row
          let scored15 = null;
          if (e._raw) {
            scored15 = Array.from({
              length: 15
            }, (_, i) => {
              const key = `tmhi_${i + 1}`;
              const raw = Number(e._raw[key]);
              if (!Number.isFinite(raw) || raw < 0 || raw > 3) return null;
              return TMHI_REVERSE_IDX.has(i) ? 3 - raw : raw;
            });
          }
          const dimScores = DIMS.map(d => {
            if (!scored15 || scored15.some(v => v == null)) return {
              key: d.key,
              raw: 0,
              pct: 0
            };
            const raw = d.items.reduce((s, i) => s + (scored15[i] ?? 0) + 1, 0);
            return {
              key: d.key,
              raw,
              pct: Math.round(raw / (d.items.length * 4) * 100)
            };
          });
          return {
            ...e,
            total: score,
            level: lvl,
            scored: scored15,
            rawAnswers: null,
            dimScores
          };
        });
      }
      return employees;
    }, [realBundle]);
    const listData = [...allEmps].sort((a, b) => a.total - b.total).filter(e => filter === "all" || e.level.key === filter);
    const lowGroup = allEmps.filter(e => e.level.key === "low");
    const midGroup = allEmps.filter(e => e.level.key === "mid");
    const highGroup = allEmps.filter(e => e.level.key === "high");
    return /*#__PURE__*/React.createElement("div", {
      style: {
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif",
        background: "#FFF7ED",
        minHeight: "100vh"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        background: "linear-gradient(135deg,#92400E 0%,#B45309 50%,#D97706 100%)",
        padding: "24px 32px 0",
        color: "#fff"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        maxWidth: 1140,
        margin: "0 auto"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 16
      }
    }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 11,
        letterSpacing: 3,
        color: "#FDE68A",
        textTransform: "uppercase",
        marginBottom: 6
      }
    }, "TMHI-15 \xB7 Thai Mental Health Indicator 2007 \xB7 \u0E21\u0E34\u0E15\u0E34\u0E2A\u0E38\u0E02\u0E20\u0E32\u0E1E\u0E08\u0E34\u0E15"), /*#__PURE__*/React.createElement("h1", {
      style: {
        margin: 0,
        fontSize: 22,
        fontWeight: 800
      }
    }, "\uD83E\uDDE0 \u0E23\u0E32\u0E22\u0E07\u0E32\u0E19\u0E2A\u0E38\u0E02\u0E20\u0E32\u0E1E\u0E08\u0E34\u0E15\u0E1A\u0E38\u0E04\u0E25\u0E32\u0E01\u0E23"), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 12,
        color: "#FDE68A",
        marginTop: 4
      }
    }, "NIDA \xB7 ", allEmps.length.toLocaleString(), " \u0E04\u0E19 \xB7 \u0E04\u0E30\u0E41\u0E19\u0E19\u0E40\u0E15\u0E47\u0E21 60 \xB7 \u0E22\u0E34\u0E48\u0E07\u0E2A\u0E39\u0E07 = \u0E2A\u0E38\u0E02\u0E20\u0E32\u0E1E\u0E08\u0E34\u0E15\u0E14\u0E35\u0E01\u0E27\u0E48\u0E32")), /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        gap: 10
      }
    }, [{
      label: "ต่ำกว่าคนทั่วไป",
      value: lowGroup.length.toLocaleString(),
      color: "#FCA5A5"
    }, {
      label: "เท่ากับคนทั่วไป",
      value: midGroup.length.toLocaleString(),
      color: "#FCD34D"
    }, {
      label: "ค่าเฉลี่ยองค์กร",
      value: Math.round(allEmps.reduce((s, e) => s + (e.total || 0), 0) / Math.max(allEmps.length, 1)) + " คะแนน",
      color: "#6EE7B7"
    }].map((s, i) => /*#__PURE__*/React.createElement("div", {
      key: i,
      style: {
        background: "rgba(255,255,255,0.12)",
        borderRadius: 12,
        padding: "10px 16px",
        textAlign: "center",
        border: "1px solid rgba(255,255,255,0.2)"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 24,
        fontWeight: 800,
        color: s.color
      }
    }, s.value), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 10,
        color: "#FDE68A"
      }
    }, s.label))))), /*#__PURE__*/React.createElement("div", {
      style: {
        background: "rgba(0,0,0,0.2)",
        borderRadius: "10px 10px 0 0",
        padding: "10px 20px",
        fontSize: 12,
        color: "#FDE68A"
      }
    }, "\uD83D\uDCCC ", /*#__PURE__*/React.createElement("strong", null, "\u0E04\u0E30\u0E41\u0E19\u0E19\u0E23\u0E27\u0E21"), " \u0E2D\u0E49\u0E32\u0E07\u0E2D\u0E34\u0E07\u0E40\u0E01\u0E13\u0E11\u0E4C\u0E01\u0E23\u0E21\u0E2A\u0E38\u0E02\u0E20\u0E32\u0E1E\u0E08\u0E34\u0E15 2550 \xB7", /*#__PURE__*/React.createElement("strong", null, " 5 \u0E21\u0E34\u0E15\u0E34\u0E40\u0E2A\u0E23\u0E34\u0E21"), " \u0E08\u0E31\u0E14\u0E01\u0E25\u0E38\u0E48\u0E21\u0E15\u0E32\u0E21\u0E40\u0E19\u0E37\u0E49\u0E2D\u0E2B\u0E32\u0E41\u0E1A\u0E1A\u0E2A\u0E2D\u0E1A\u0E16\u0E32\u0E21 \u0E44\u0E21\u0E48\u0E43\u0E0A\u0E48 sub-scale \u0E21\u0E32\u0E15\u0E23\u0E10\u0E32\u0E19 \xB7 \u0E02\u0E49\u0E2D 4-6 \u0E04\u0E34\u0E14\u0E04\u0E30\u0E41\u0E19\u0E19 Reverse \u0E41\u0E25\u0E49\u0E27"), /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        gap: 4
      }
    }, [{
      key: "overview",
      label: "🏢 ภาพรวมองค์กร"
    }, {
      key: "risklist",
      label: "📋 Risk List"
    }, {
      key: "individual",
      label: "👤 IDP รายบุคคล"
    }].map(t => /*#__PURE__*/React.createElement("button", {
      key: t.key,
      onClick: () => setTab(t.key),
      style: {
        padding: "10px 20px",
        borderRadius: "8px 8px 0 0",
        border: "none",
        cursor: "pointer",
        fontSize: 13,
        fontWeight: 700,
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif",
        background: tab === t.key ? "#FFF7ED" : "transparent",
        color: tab === t.key ? "#92400E" : "rgba(255,255,255,0.65)"
      }
    }, t.label))))), /*#__PURE__*/React.createElement("div", {
      style: {
        maxWidth: 1140,
        margin: "0 auto",
        padding: "24px 32px"
      }
    }, tab === "overview" && /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        flexDirection: "column",
        gap: 20
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#fff",
        borderRadius: 16,
        padding: 24,
        boxShadow: "0 1px 3px rgba(0,0,0,0.08)"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        marginBottom: 6
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        width: 4,
        height: 20,
        background: "#D97706",
        borderRadius: 2
      }
    }), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 15,
        fontWeight: 800,
        color: "#92400E"
      }
    }, "\u0E04\u0E30\u0E41\u0E19\u0E19\u0E23\u0E27\u0E21 \u2014 3 \u0E23\u0E30\u0E14\u0E31\u0E1A (\u0E40\u0E01\u0E13\u0E11\u0E4C\u0E01\u0E23\u0E21\u0E2A\u0E38\u0E02\u0E20\u0E32\u0E1E\u0E08\u0E34\u0E15 2550)")), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 11,
        color: "#9CA3AF",
        marginBottom: 20,
        marginLeft: 14
      }
    }, "\u0E43\u0E0A\u0E49\u0E40\u0E1B\u0E47\u0E19\u0E40\u0E01\u0E13\u0E11\u0E4C\u0E2B\u0E25\u0E31\u0E01\u0E43\u0E19\u0E01\u0E32\u0E23\u0E08\u0E31\u0E14\u0E01\u0E25\u0E38\u0E48\u0E21\u0E04\u0E27\u0E32\u0E21\u0E40\u0E2A\u0E35\u0E48\u0E22\u0E07 \xB7 \u0E22\u0E34\u0E48\u0E07\u0E2A\u0E39\u0E07 = \u0E2A\u0E38\u0E02\u0E20\u0E32\u0E1E\u0E08\u0E34\u0E15\u0E14\u0E35\u0E01\u0E27\u0E48\u0E32"), /*#__PURE__*/React.createElement("div", {
      style: {
        display: "grid",
        gridTemplateColumns: "repeat(3,1fr) 1fr",
        gap: 16
      }
    }, LEVEL_CFG.map(lvl => {
      const count = allEmps.filter(e => e.level.key === lvl.key).length;
      const p = Math.round(count / Math.max(allEmps.length, 1) * 100);
      return /*#__PURE__*/React.createElement("div", {
        key: lvl.key,
        style: {
          background: lvl.bg,
          borderRadius: 14,
          padding: "20px 22px",
          border: `1px solid ${lvl.color}33`
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 11,
          color: "#6B7280",
          marginBottom: 4
        }
      }, lvl.range, " \u0E04\u0E30\u0E41\u0E19\u0E19"), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 34,
          fontWeight: 800,
          color: lvl.color
        }
      }, count), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 13,
          fontWeight: 700,
          color: lvl.color
        }
      }, lvl.label), /*#__PURE__*/React.createElement("div", {
        style: {
          height: 6,
          background: lvl.color + "22",
          borderRadius: 3,
          marginTop: 10,
          overflow: "hidden"
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          width: `${p}%`,
          height: "100%",
          background: lvl.color
        }
      })), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 11,
          color: "#9CA3AF",
          marginTop: 6
        }
      }, p, "% \u0E02\u0E2D\u0E07\u0E17\u0E31\u0E49\u0E07\u0E2B\u0E21\u0E14"));
    }), /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#FFF7ED",
        borderRadius: 14,
        padding: "20px 22px",
        border: "1px solid #FDE68A",
        textAlign: "center"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 11,
        color: "#9CA3AF",
        marginBottom: 4
      }
    }, "\u0E04\u0E48\u0E32\u0E40\u0E09\u0E25\u0E35\u0E48\u0E22\u0E2D\u0E07\u0E04\u0E4C\u0E01\u0E23"), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 34,
        fontWeight: 800,
        color: "#D97706"
      }
    }, Math.round(allEmps.reduce((s, e) => s + (e.total || 0), 0) / Math.max(allEmps.length, 1))), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 12,
        color: "#D97706"
      }
    }, "/ 60 \u0E04\u0E30\u0E41\u0E19\u0E19"), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 11,
        color: getLevel(Math.round(allEmps.reduce((s, e) => s + (e.total || 0), 0) / Math.max(allEmps.length, 1))).color,
        fontWeight: 700,
        marginTop: 6
      }
    }, "\u2192 ", getLevel(Math.round(allEmps.reduce((s, e) => s + (e.total || 0), 0) / Math.max(allEmps.length, 1))).label))), /*#__PURE__*/React.createElement("div", {
      style: {
        marginTop: 24
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 13,
        fontWeight: 700,
        color: "#374151",
        marginBottom: 12
      }
    }, "\u0E41\u0E22\u0E01\u0E15\u0E32\u0E21\u0E2B\u0E19\u0E48\u0E27\u0E22\u0E07\u0E32\u0E19"), /*#__PURE__*/React.createElement(ResponsiveContainer, {
      width: "100%",
      height: 180
    }, /*#__PURE__*/React.createElement(BarChart, {
      data: (() => {
        const depts = [...new Set(allEmps.map(e => e.dept || e.org || 'ไม่ระบุ'))].slice(0, 8);
        return depts.map(d => ({
          name: d,
          'ดีกว่าคนทั่วไป': allEmps.filter(e => (e.dept || e.org || 'ไม่ระบุ') === d && e.level.key === 'high').length,
          'เท่ากับคนทั่วไป': allEmps.filter(e => (e.dept || e.org || 'ไม่ระบุ') === d && e.level.key === 'mid').length,
          'ต่ำกว่าคนทั่วไป': allEmps.filter(e => (e.dept || e.org || 'ไม่ระบุ') === d && e.level.key === 'low').length
        }));
      })(),
      barSize: 52,
      margin: {
        top: 0,
        right: 0,
        left: -20,
        bottom: 0
      }
    }, /*#__PURE__*/React.createElement(CartesianGrid, {
      strokeDasharray: "3 3",
      stroke: "#F3F4F6",
      vertical: false
    }), /*#__PURE__*/React.createElement(XAxis, {
      dataKey: "name",
      tick: {
        fill: "#6B7280",
        fontSize: 13,
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif"
      },
      axisLine: false,
      tickLine: false
    }), /*#__PURE__*/React.createElement(YAxis, {
      tick: {
        fill: "#9CA3AF",
        fontSize: 11
      },
      axisLine: false,
      tickLine: false
    }), /*#__PURE__*/React.createElement(Tooltip, {
      content: /*#__PURE__*/React.createElement(CustomTooltip, null),
      cursor: {
        fill: "rgba(0,0,0,0.02)"
      }
    }), /*#__PURE__*/React.createElement(Bar, {
      dataKey: "\u0E15\u0E48\u0E33\u0E01\u0E27\u0E48\u0E32\u0E04\u0E19\u0E17\u0E31\u0E48\u0E27\u0E44\u0E1B",
      stackId: "a",
      fill: "#EF4444"
    }), /*#__PURE__*/React.createElement(Bar, {
      dataKey: "\u0E40\u0E17\u0E48\u0E32\u0E01\u0E31\u0E1A\u0E04\u0E19\u0E17\u0E31\u0E48\u0E27\u0E44\u0E1B",
      stackId: "a",
      fill: "#F59E0B"
    }), /*#__PURE__*/React.createElement(Bar, {
      dataKey: "\u0E14\u0E35\u0E01\u0E27\u0E48\u0E32\u0E04\u0E19\u0E17\u0E31\u0E48\u0E27\u0E44\u0E1B",
      stackId: "a",
      fill: "#10B981",
      radius: [4, 4, 0, 0]
    }), /*#__PURE__*/React.createElement(Legend, {
      wrapperStyle: {
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif",
        fontSize: 12
      }
    }))))), /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#fff",
        borderRadius: 16,
        padding: 24,
        boxShadow: "0 1px 3px rgba(0,0,0,0.08)"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        marginBottom: 6
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        width: 4,
        height: 20,
        background: "#9CA3AF",
        borderRadius: 2
      }
    }), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 15,
        fontWeight: 800,
        color: "#374151"
      }
    }, "5 \u0E21\u0E34\u0E15\u0E34\u0E40\u0E2A\u0E23\u0E34\u0E21 \u2014 \u0E43\u0E0A\u0E49\u0E40\u0E1E\u0E37\u0E48\u0E2D\u0E2D\u0E2D\u0E01\u0E41\u0E1A\u0E1A IDP")), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 11,
        color: "#9CA3AF",
        marginBottom: 20,
        marginLeft: 14
      }
    }, "\u0E08\u0E31\u0E14\u0E01\u0E25\u0E38\u0E48\u0E21\u0E15\u0E32\u0E21\u0E40\u0E19\u0E37\u0E49\u0E2D\u0E2B\u0E32\u0E41\u0E1A\u0E1A\u0E2A\u0E2D\u0E1A\u0E16\u0E32\u0E21 \u0E44\u0E21\u0E48\u0E43\u0E0A\u0E48 sub-scale \u0E21\u0E32\u0E15\u0E23\u0E10\u0E32\u0E19 \xB7 \u0E43\u0E0A\u0E49\u0E14\u0E39\u0E27\u0E48\u0E32 \"\u0E2D\u0E07\u0E04\u0E4C\u0E01\u0E23\u0E19\u0E35\u0E49\u0E2D\u0E48\u0E2D\u0E19\u0E14\u0E49\u0E32\u0E19\u0E44\u0E2B\u0E19\""), /*#__PURE__*/React.createElement("div", {
      style: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: 20
      }
    }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 12,
        fontWeight: 700,
        color: "#374151",
        marginBottom: 8
      }
    }, "Radar: \u0E42\u0E1B\u0E23\u0E44\u0E1F\u0E25\u0E4C 5 \u0E21\u0E34\u0E15\u0E34 \u2014 \u0E15\u0E48\u0E33\u0E01\u0E27\u0E48\u0E32\u0E04\u0E19\u0E17\u0E31\u0E48\u0E27\u0E44\u0E1B vs \u0E04\u0E48\u0E32\u0E40\u0E09\u0E25\u0E35\u0E48\u0E22\u0E2D\u0E07\u0E04\u0E4C\u0E01\u0E23 (%)"), /*#__PURE__*/React.createElement(ResponsiveContainer, {
      width: "100%",
      height: 280
    }, /*#__PURE__*/React.createElement(RadarChart, {
      data: DIMS.map(d => {
        const lGrp = allEmps.filter(e => e.level.key === "low");
        const dPct = allEmps.length > 0 ? Math.round(allEmps.reduce((s, e) => s + (e.dimScores?.find(x => x.key === d.key)?.pct || 0), 0) / allEmps.length) : 0;
        const lPct = lGrp.length > 0 ? Math.round(lGrp.reduce((s, e) => s + (e.dimScores?.find(x => x.key === d.key)?.pct || 0), 0) / lGrp.length) : 0;
        return {
          dim: d.icon + " " + d.short,
          'ต่ำกว่าคนทั่วไป (≤43)': lPct,
          'ค่าเฉลี่ยองค์กร': dPct
        };
      })
    }, /*#__PURE__*/React.createElement(PolarGrid, {
      stroke: "#E5E7EB"
    }), /*#__PURE__*/React.createElement(PolarAngleAxis, {
      dataKey: "dim",
      tick: {
        fill: "#6B7280",
        fontSize: 11,
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif"
      }
    }), /*#__PURE__*/React.createElement(PolarRadiusAxis, {
      domain: [0, 100],
      tick: false,
      axisLine: false
    }), /*#__PURE__*/React.createElement(Radar, {
      name: "\u0E01\u0E25\u0E38\u0E48\u0E21\u0E15\u0E48\u0E33\u0E01\u0E27\u0E48\u0E32\u0E04\u0E19\u0E17\u0E31\u0E48\u0E27\u0E44\u0E1B",
      dataKey: "\u0E15\u0E48\u0E33\u0E01\u0E27\u0E48\u0E32\u0E04\u0E19\u0E17\u0E31\u0E48\u0E27\u0E44\u0E1B (\u226443)",
      stroke: "#EF4444",
      fill: "#EF4444",
      fillOpacity: 0.2,
      strokeWidth: 2,
      dot: {
        fill: "#EF4444",
        r: 4
      }
    }), /*#__PURE__*/React.createElement(Radar, {
      name: "\u0E04\u0E48\u0E32\u0E40\u0E09\u0E25\u0E35\u0E48\u0E22\u0E2D\u0E07\u0E04\u0E4C\u0E01\u0E23",
      dataKey: "\u0E04\u0E48\u0E32\u0E40\u0E09\u0E25\u0E35\u0E48\u0E22\u0E2D\u0E07\u0E04\u0E4C\u0E01\u0E23",
      stroke: "#D97706",
      fill: "#D97706",
      fillOpacity: 0.1,
      strokeWidth: 1.5,
      strokeDasharray: "4 3",
      dot: {
        fill: "#D97706",
        r: 3
      }
    }), /*#__PURE__*/React.createElement(Legend, {
      wrapperStyle: {
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif",
        fontSize: 12
      }
    })))), /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        flexDirection: "column",
        gap: 10
      }
    }, DIMS.map(d => {
      const orgPct = allEmps.length > 0 ? Math.round(allEmps.reduce((s, e) => s + (e.dimScores?.find(x => x.key === d.key)?.pct || 0), 0) / allEmps.length) : 0;
      const lowPct = lowGroup.length > 0 ? Math.round(lowGroup.reduce((s, e) => s + (e.dimScores?.find(x => x.key === d.key)?.pct || 0), 0) / lowGroup.length) : 0;
      const sev = orgPct <= 50 ? "ต่ำ" : orgPct <= 70 ? "ปานกลาง" : "สูง";
      const sevColor = orgPct <= 50 ? "#EF4444" : orgPct <= 70 ? "#F59E0B" : "#10B981";
      return /*#__PURE__*/React.createElement("div", {
        key: d.key,
        style: {
          background: "#F9FAFB",
          borderRadius: 10,
          padding: "12px 14px",
          borderLeft: `4px solid ${d.color}`
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          display: "flex",
          justifyContent: "space-between",
          marginBottom: 6
        }
      }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 12,
          fontWeight: 700,
          color: "#374151"
        }
      }, d.icon, " ", d.label), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 10,
          color: "#9CA3AF"
        }
      }, d.desc)), /*#__PURE__*/React.createElement("div", {
        style: {
          textAlign: "right"
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 18,
          fontWeight: 800,
          color: d.color
        }
      }, orgPct, "%"), /*#__PURE__*/React.createElement(Tag, {
        label: sev,
        color: sevColor,
        small: true
      }))), /*#__PURE__*/React.createElement("div", {
        style: {
          display: "flex",
          alignItems: "center",
          gap: 8
        }
      }, /*#__PURE__*/React.createElement("span", {
        style: {
          fontSize: 10,
          color: "#9CA3AF",
          width: 60
        }
      }, "\u0E17\u0E31\u0E49\u0E07\u0E2D\u0E07\u0E04\u0E4C\u0E01\u0E23"), /*#__PURE__*/React.createElement(MiniBar, {
        pct: orgPct,
        color: d.color
      }), /*#__PURE__*/React.createElement("span", {
        style: {
          fontSize: 10,
          color: "#9CA3AF",
          width: 28
        }
      }, orgPct, "%")), /*#__PURE__*/React.createElement("div", {
        style: {
          display: "flex",
          alignItems: "center",
          gap: 8,
          marginTop: 5
        }
      }, /*#__PURE__*/React.createElement("span", {
        style: {
          fontSize: 10,
          color: "#EF4444",
          width: 60
        }
      }, "\u0E01\u0E25\u0E38\u0E48\u0E21\u0E40\u0E2A\u0E35\u0E48\u0E22\u0E07"), /*#__PURE__*/React.createElement(MiniBar, {
        pct: lowPct,
        color: "#EF4444"
      }), /*#__PURE__*/React.createElement("span", {
        style: {
          fontSize: 10,
          color: "#EF4444",
          width: 28
        }
      }, lowPct, "%")), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 10,
          color: "#6B7280",
          marginTop: 6
        }
      }, "\uD83D\uDCA1 ", d.key === "happiness" ? "Gratitude Journal / Mindfulness" : d.key === "stress" ? "จัดการความเครียด / EAP / Resilience" : d.key === "selfmgmt" ? "EQ Training / Coaching" : d.key === "empathy" ? "กิจกรรมอาสา / Mentor Program" : "Work-Life Balance / Family Day"));
    })))), /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#fff",
        borderRadius: 16,
        padding: 24,
        boxShadow: "0 1px 3px rgba(0,0,0,0.08)"
      }
    }, /*#__PURE__*/React.createElement(HeatmapTableTMHI, {
      empArray: allEmps
    }))), tab === "risklist" && /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        flexDirection: "column",
        gap: 16
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#fff",
        borderRadius: 14,
        padding: "14px 20px",
        boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
        display: "flex",
        gap: 10,
        alignItems: "center"
      }
    }, /*#__PURE__*/React.createElement("span", {
      style: {
        fontSize: 13,
        color: "#6B7280",
        fontWeight: 600
      }
    }, "\u0E01\u0E23\u0E2D\u0E07\u0E01\u0E25\u0E38\u0E48\u0E21:"), [["all", "ทั้งหมด", "#D97706"], ["low", "🔴 ต่ำกว่าคนทั่วไป", "#EF4444"], ["mid", "🟡 เท่ากับ", "#F59E0B"], ["high", "🟢 ดีกว่า", "#10B981"]].map(([key, label, color]) => /*#__PURE__*/React.createElement("button", {
      key: key,
      onClick: () => setFilter(key),
      style: {
        padding: "6px 14px",
        borderRadius: 999,
        fontSize: 12,
        fontWeight: 700,
        fontFamily: "'IBM Plex Sans Thai Looped',sans-serif",
        cursor: "pointer",
        border: "none",
        background: filter === key ? color : "#F3F4F6",
        color: filter === key ? "#fff" : "#6B7280"
      }
    }, label)), /*#__PURE__*/React.createElement("span", {
      style: {
        marginLeft: "auto",
        fontSize: 12,
        color: "#9CA3AF"
      }
    }, "\u0E41\u0E2A\u0E14\u0E07 ", listData.length, " \u0E04\u0E19")), /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#fff",
        borderRadius: 14,
        overflow: "hidden",
        boxShadow: "0 1px 3px rgba(0,0,0,0.06)"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        display: "grid",
        gridTemplateColumns: "28px 1fr 100px 100px 56px 56px 56px 56px 56px 100px",
        padding: "10px 20px",
        background: "#F9FAFB",
        borderBottom: "1px solid #F3F4F6",
        gap: 6
      }
    }, ["#", "ชื่อ", "หน่วยงาน", "ระดับ", "😊", "💪", "🎯", "🤝", "🏠", "คะแนนรวม"].map((h, i) => /*#__PURE__*/React.createElement("div", {
      key: i,
      style: {
        fontSize: 10,
        fontWeight: 700,
        color: "#9CA3AF",
        textTransform: "uppercase",
        letterSpacing: 0.5
      }
    }, h))), listData.map((emp, idx) => /*#__PURE__*/React.createElement("div", {
      key: emp.id,
      onClick: () => {
        setSelectedEmp(emp);
        setTab("individual");
      },
      style: {
        display: "grid",
        gridTemplateColumns: "28px 1fr 100px 100px 56px 56px 56px 56px 56px 100px",
        padding: "12px 20px",
        gap: 6,
        cursor: "pointer",
        borderBottom: "1px solid #F9FAFB",
        background: idx % 2 === 0 ? "#fff" : "#FAFAFA",
        borderLeft: `3px solid ${emp.level.color}`,
        transition: "background 0.15s"
      },
      onMouseEnter: e => e.currentTarget.style.background = "#FFF7ED",
      onMouseLeave: e => e.currentTarget.style.background = idx % 2 === 0 ? "#fff" : "#FAFAFA"
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 11,
        color: "#9CA3AF",
        alignSelf: "center"
      }
    }, idx + 1), /*#__PURE__*/React.createElement("div", {
      style: {
        alignSelf: "center"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 13,
        fontWeight: 700,
        color: "#111827"
      }
    }, emp.name), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 10,
        color: "#9CA3AF"
      }
    }, emp.dept)), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 12,
        color: "#6B7280",
        alignSelf: "center"
      }
    }, emp.dept), /*#__PURE__*/React.createElement("div", {
      style: {
        alignSelf: "center"
      }
    }, /*#__PURE__*/React.createElement(Tag, {
      label: emp.level.label,
      color: emp.level.color,
      small: true
    })), DIMS.map(d => {
      const ds = emp.dimScores.find(x => x.key === d.key);
      return /*#__PURE__*/React.createElement("div", {
        key: d.key,
        style: {
          alignSelf: "center"
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 11,
          fontWeight: 700,
          color: d.color
        }
      }, ds.pct, "%"), /*#__PURE__*/React.createElement("div", {
        style: {
          width: 36,
          height: 4,
          background: "#F3F4F6",
          borderRadius: 2,
          overflow: "hidden",
          marginTop: 3
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          width: `${ds.pct}%`,
          height: "100%",
          background: d.color
        }
      })));
    }), /*#__PURE__*/React.createElement("div", {
      style: {
        alignSelf: "center",
        textAlign: "right"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 18,
        fontWeight: 800,
        color: emp.level.color
      }
    }, emp.total), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 10,
        color: "#9CA3AF"
      }
    }, "/ 60"))))), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 11,
        color: "#9CA3AF",
        textAlign: "center"
      }
    }, "\u0E44\u0E2D\u0E04\u0E2D\u0E19 \uD83D\uDE0A\uD83D\uDCAA\uD83C\uDFAF\uD83E\uDD1D\uD83C\uDFE0 = 5 \u0E21\u0E34\u0E15\u0E34\u0E40\u0E2A\u0E23\u0E34\u0E21 (%) \xB7 \u0E04\u0E30\u0E41\u0E19\u0E19\u0E23\u0E27\u0E21 = \u0E40\u0E01\u0E13\u0E11\u0E4C\u0E2B\u0E25\u0E31\u0E01 \xB7 \u0E04\u0E25\u0E34\u0E01\u0E0A\u0E37\u0E48\u0E2D\u0E40\u0E1E\u0E37\u0E48\u0E2D\u0E14\u0E39 IDP")), tab === "individual" && /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        gap: 20
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        width: 260,
        flexShrink: 0
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 12,
        fontWeight: 700,
        color: "#6B7280",
        marginBottom: 10
      }
    }, "\u0E40\u0E23\u0E35\u0E22\u0E07\u0E08\u0E32\u0E01\u0E04\u0E30\u0E41\u0E19\u0E19\u0E15\u0E48\u0E33\u0E2A\u0E38\u0E14 (\u0E40\u0E2A\u0E35\u0E48\u0E22\u0E07\u0E2A\u0E38\u0E14)"), /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        flexDirection: "column",
        gap: 6,
        maxHeight: 680,
        overflowY: "auto"
      }
    }, [...allEmps].sort((a, b) => a.total - b.total).map(emp => {
      const isSelected = selectedEmp?.id === emp.id;
      return /*#__PURE__*/React.createElement("div", {
        key: emp.id,
        onClick: () => setSelectedEmp(emp),
        style: {
          background: isSelected ? "#FFF7ED" : "#fff",
          borderRadius: 10,
          padding: "10px 14px",
          cursor: "pointer",
          border: `1px solid ${isSelected ? "#D97706" : "#E5E7EB"}`,
          transition: "all 0.15s"
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start"
        }
      }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 12,
          fontWeight: 700,
          color: "#111827"
        }
      }, emp.name), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 10,
          color: "#9CA3AF"
        }
      }, emp.dept)), /*#__PURE__*/React.createElement("div", {
        style: {
          textAlign: "right"
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 18,
          fontWeight: 800,
          color: emp.level.color
        }
      }, emp.total), /*#__PURE__*/React.createElement(Tag, {
        label: emp.level.label,
        color: emp.level.color,
        small: true
      }))), /*#__PURE__*/React.createElement("div", {
        style: {
          display: "flex",
          gap: 4,
          marginTop: 8
        }
      }, DIMS.map(d => {
        const ds = emp.dimScores.find(x => x.key === d.key);
        return /*#__PURE__*/React.createElement("div", {
          key: d.key,
          style: {
            flex: 1
          }
        }, /*#__PURE__*/React.createElement("div", {
          style: {
            fontSize: 9,
            color: d.color,
            textAlign: "center",
            marginBottom: 2
          }
        }, d.icon), /*#__PURE__*/React.createElement("div", {
          style: {
            height: 4,
            background: "#F3F4F6",
            borderRadius: 2,
            overflow: "hidden"
          }
        }, /*#__PURE__*/React.createElement("div", {
          style: {
            width: `${ds.pct}%`,
            height: "100%",
            background: d.color
          }
        })));
      })));
    }))), /*#__PURE__*/React.createElement("div", {
      style: {
        flex: 1
      }
    }, !selectedEmp ? /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#fff",
        borderRadius: 16,
        padding: 60,
        textAlign: "center",
        color: "#9CA3AF",
        boxShadow: "0 1px 3px rgba(0,0,0,0.06)"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 48,
        marginBottom: 16
      }
    }, "\uD83E\uDDE0"), /*#__PURE__*/React.createElement("div", null, "\u0E40\u0E25\u0E37\u0E2D\u0E01\u0E0A\u0E37\u0E48\u0E2D\u0E14\u0E49\u0E32\u0E19\u0E0B\u0E49\u0E32\u0E22\u0E40\u0E1E\u0E37\u0E48\u0E2D\u0E14\u0E39\u0E23\u0E32\u0E22\u0E25\u0E30\u0E40\u0E2D\u0E35\u0E22\u0E14 IDP")) : /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        flexDirection: "column",
        gap: 16
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#fff",
        borderRadius: 16,
        padding: 24,
        boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
        borderTop: `4px solid ${selectedEmp.level.color}`
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        gap: 28,
        alignItems: "center"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        textAlign: "center",
        flexShrink: 0
      }
    }, /*#__PURE__*/React.createElement(Gauge, {
      score: selectedEmp.total,
      size: 200
    }), /*#__PURE__*/React.createElement("div", {
      style: {
        background: selectedEmp.level.bg,
        border: `1px solid ${selectedEmp.level.color}55`,
        borderRadius: 10,
        padding: "6px 16px",
        marginTop: 6,
        display: "inline-block"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 13,
        fontWeight: 800,
        color: selectedEmp.level.color
      }
    }, selectedEmp.level.label), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 10,
        color: "#9CA3AF"
      }
    }, selectedEmp.level.range, " \u0E04\u0E30\u0E41\u0E19\u0E19"))), /*#__PURE__*/React.createElement("div", {
      style: {
        flex: 1
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 20,
        fontWeight: 800,
        color: "#111827"
      }
    }, selectedEmp.name), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 13,
        color: "#6B7280",
        marginBottom: 20
      }
    }, selectedEmp.dept), /*#__PURE__*/React.createElement("div", {
      style: {
        marginBottom: 16
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        justifyContent: "space-between",
        marginBottom: 6
      }
    }, /*#__PURE__*/React.createElement("span", {
      style: {
        fontSize: 12,
        color: "#6B7280"
      }
    }, "\u0E04\u0E30\u0E41\u0E19\u0E19\u0E23\u0E27\u0E21 TMHI-15"), /*#__PURE__*/React.createElement("span", {
      style: {
        fontSize: 14,
        fontWeight: 800,
        color: selectedEmp.level.color
      }
    }, selectedEmp.total, " / 60")), /*#__PURE__*/React.createElement("div", {
      style: {
        height: 12,
        background: "#F3F4F6",
        borderRadius: 6,
        overflow: "hidden",
        position: "relative"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        position: "absolute",
        left: `${43 / 60 * 100}%`,
        top: 0,
        width: 2,
        height: "100%",
        background: "#9CA3AF"
      }
    }), /*#__PURE__*/React.createElement("div", {
      style: {
        position: "absolute",
        left: `${50 / 60 * 100}%`,
        top: 0,
        width: 2,
        height: "100%",
        background: "#9CA3AF"
      }
    }), /*#__PURE__*/React.createElement("div", {
      style: {
        width: `${selectedEmp.total / 60 * 100}%`,
        height: "100%",
        background: selectedEmp.level.color,
        borderRadius: 6
      }
    })), /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        justifyContent: "space-between",
        fontSize: 10,
        color: "#9CA3AF",
        marginTop: 3
      }
    }, /*#__PURE__*/React.createElement("span", null, "0 \u0E15\u0E48\u0E33\u0E01\u0E27\u0E48\u0E32"), /*#__PURE__*/React.createElement("span", null, "44 \u0E40\u0E17\u0E48\u0E32\u0E01\u0E31\u0E19"), /*#__PURE__*/React.createElement("span", null, "51 \u0E14\u0E35\u0E01\u0E27\u0E48\u0E32"), /*#__PURE__*/React.createElement("span", null, "60"))), /*#__PURE__*/React.createElement("div", {
      style: {
        display: "grid",
        gridTemplateColumns: "repeat(5,1fr)",
        gap: 8
      }
    }, DIMS.map(d => {
      const ds = selectedEmp.dimScores.find(x => x.key === d.key);
      const lvl = ds.pct <= 50 ? "ต่ำ" : ds.pct <= 70 ? "กลาง" : "สูง";
      const lvlColor = ds.pct <= 50 ? "#EF4444" : ds.pct <= 70 ? "#F59E0B" : "#10B981";
      return /*#__PURE__*/React.createElement("div", {
        key: d.key,
        style: {
          background: "#F9FAFB",
          borderRadius: 8,
          padding: "8px 6px",
          textAlign: "center",
          borderTop: `3px solid ${d.color}`
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 16
        }
      }, d.icon), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 9,
          color: "#6B7280",
          margin: "3px 0"
        }
      }, d.short), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 16,
          fontWeight: 800,
          color: d.color
        }
      }, ds.pct, "%"), /*#__PURE__*/React.createElement(Tag, {
        label: lvl,
        color: lvlColor,
        small: true
      }));
    }))))), /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#fff",
        borderRadius: 14,
        padding: 22,
        boxShadow: "0 1px 3px rgba(0,0,0,0.06)"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 14,
        fontWeight: 800,
        color: "#92400E",
        marginBottom: 6
      }
    }, "\uD83D\uDCDD \u0E27\u0E34\u0E40\u0E04\u0E23\u0E32\u0E30\u0E2B\u0E4C\u0E23\u0E32\u0E22\u0E02\u0E49\u0E2D \u2014 \u0E40\u0E1E\u0E37\u0E48\u0E2D\u0E2D\u0E2D\u0E01\u0E41\u0E1A\u0E1A IDP"), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 11,
        color: "#9CA3AF",
        marginBottom: 16
      }
    }, "\u0E41\u0E2A\u0E14\u0E07\u0E40\u0E09\u0E1E\u0E32\u0E30\u0E02\u0E49\u0E2D\u0E17\u0E35\u0E48\u0E04\u0E30\u0E41\u0E19\u0E19\u0E15\u0E48\u0E33 (\u22642 \u0E08\u0E32\u0E01 4) \xB7 \u0E08\u0E31\u0E14\u0E01\u0E25\u0E38\u0E48\u0E21\u0E15\u0E32\u0E21 5 \u0E21\u0E34\u0E15\u0E34\u0E40\u0E2A\u0E23\u0E34\u0E21 \xB7 (R) = \u0E02\u0E49\u0E2D Reverse \u0E41\u0E1B\u0E25\u0E07\u0E04\u0E30\u0E41\u0E19\u0E19\u0E41\u0E25\u0E49\u0E27"), DIMS.map(d => {
      const getItemScore = i => {
        if (selectedEmp.scored) return selectedEmp.scored[i];
        if (selectedEmp._raw) {
          const raw = Number(selectedEmp._raw[`tmhi_${i + 1}`]);
          if (!Number.isFinite(raw) || raw < 0 || raw > 3) return null;
          return TMHI_REVERSE_IDX.has(i) ? 3 - raw : raw;
        }
        return null;
      };
      const lowItems = d.items.map(i => ({
        idx: i,
        label: ITEM_LABELS[i],
        score: getItemScore(i),
        isReverse: i >= 3 && i <= 5
      })).filter(item => item.score != null && item.score <= 2);
      if (lowItems.length === 0) return /*#__PURE__*/React.createElement("div", {
        key: d.key,
        style: {
          display: "flex",
          alignItems: "center",
          gap: 10,
          padding: "10px 0",
          borderBottom: "1px solid #F3F4F6"
        }
      }, /*#__PURE__*/React.createElement("span", {
        style: {
          fontSize: 16
        }
      }, d.icon), /*#__PURE__*/React.createElement("span", {
        style: {
          fontSize: 12,
          color: "#6B7280"
        }
      }, d.label), /*#__PURE__*/React.createElement(Tag, {
        label: "\u2713 \u0E44\u0E21\u0E48\u0E21\u0E35\u0E02\u0E49\u0E2D\u0E17\u0E35\u0E48\u0E19\u0E48\u0E32\u0E01\u0E31\u0E07\u0E27\u0E25",
        color: "#10B981",
        small: true
      }));
      return /*#__PURE__*/React.createElement("div", {
        key: d.key,
        style: {
          marginBottom: 16,
          borderBottom: "1px solid #F3F4F6",
          paddingBottom: 16
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          display: "flex",
          alignItems: "center",
          gap: 8,
          marginBottom: 10
        }
      }, /*#__PURE__*/React.createElement("span", {
        style: {
          fontSize: 18
        }
      }, d.icon), /*#__PURE__*/React.createElement("span", {
        style: {
          fontSize: 13,
          fontWeight: 700,
          color: d.color
        }
      }, d.label), /*#__PURE__*/React.createElement(Tag, {
        label: `${lowItems.length} ข้อน่ากังวล`,
        color: d.color,
        small: true
      })), lowItems.map(item => /*#__PURE__*/React.createElement("div", {
        key: item.idx,
        style: {
          background: item.score === 1 ? "#FEF2F2" : "#FFFBEB",
          borderRadius: 8,
          padding: "10px 12px",
          marginBottom: 8,
          borderLeft: `3px solid ${item.score === 1 ? "#EF4444" : "#F59E0B"}`
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          display: "flex",
          justifyContent: "space-between",
          marginBottom: 6
        }
      }, /*#__PURE__*/React.createElement("span", {
        style: {
          fontSize: 12,
          color: "#374151",
          fontWeight: 600
        }
      }, item.label, item.isReverse && /*#__PURE__*/React.createElement("span", {
        style: {
          fontSize: 10,
          color: "#6366F1",
          marginLeft: 6
        }
      }, "(R)")), /*#__PURE__*/React.createElement("span", {
        style: {
          background: item.score === 1 ? "#EF4444" : "#F59E0B",
          color: "#fff",
          padding: "1px 8px",
          borderRadius: 999,
          fontSize: 10,
          fontWeight: 700,
          flexShrink: 0,
          marginLeft: 8
        }
      }, item.score, "/4")), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 11,
          color: "#6B7280"
        }
      }, "\uD83D\uDCA1 ", IDP_MAP[item.idx]))));
    })), /*#__PURE__*/React.createElement("div", {
      style: {
        background: "#FFF7ED",
        borderRadius: 12,
        padding: "16px 20px",
        border: "1px solid #FDE68A"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 13,
        fontWeight: 800,
        color: "#92400E",
        marginBottom: 12
      }
    }, "\uD83C\uDFAF \u0E25\u0E33\u0E14\u0E31\u0E1A\u0E04\u0E27\u0E32\u0E21\u0E2A\u0E33\u0E04\u0E31\u0E0D IDP \u0E21\u0E34\u0E15\u0E34\u0E2A\u0E38\u0E02\u0E20\u0E32\u0E1E\u0E08\u0E34\u0E15 \u2014 ", selectedEmp.name), /*#__PURE__*/React.createElement("div", {
      style: {
        display: "flex",
        gap: 10,
        flexWrap: "wrap"
      }
    }, selectedEmp.level.key === "low" && /*#__PURE__*/React.createElement("div", {
      style: {
        flex: 1,
        minWidth: 160,
        background: "#FEF2F2",
        borderRadius: 10,
        padding: "12px 14px",
        borderLeft: "3px solid #EF4444"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 10,
        fontWeight: 700,
        color: "#EF4444"
      }
    }, "\u0E14\u0E48\u0E27\u0E19 \uD83D\uDD34"), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 12,
        fontWeight: 700,
        color: "#374151",
        marginTop: 4
      }
    }, "\u0E1E\u0E1A\u0E19\u0E31\u0E01\u0E08\u0E34\u0E15\u0E27\u0E34\u0E17\u0E22\u0E32 / EAP"), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 11,
        color: "#6B7280",
        marginTop: 4
      }
    }, "\u0E04\u0E30\u0E41\u0E19\u0E19\u0E15\u0E48\u0E33\u0E01\u0E27\u0E48\u0E32\u0E04\u0E19\u0E17\u0E31\u0E48\u0E27\u0E44\u0E1B \u0E04\u0E27\u0E23\u0E1B\u0E23\u0E30\u0E40\u0E21\u0E34\u0E19\u0E40\u0E1E\u0E34\u0E48\u0E21\u0E40\u0E15\u0E34\u0E21")), DIMS.map(d => {
      const ds = selectedEmp.dimScores.find(x => x.key === d.key);
      if (ds.pct > 50) return null;
      return /*#__PURE__*/React.createElement("div", {
        key: d.key,
        style: {
          flex: 1,
          minWidth: 140,
          background: "#fff",
          borderRadius: 10,
          padding: "12px 14px",
          borderLeft: `3px solid ${d.color}`,
          border: `1px solid ${d.color}33`,
          borderLeftWidth: 3
        }
      }, /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 10,
          fontWeight: 700,
          color: d.color
        }
      }, d.icon, " ", d.short), /*#__PURE__*/React.createElement("div", {
        style: {
          fontSize: 11,
          color: "#374151",
          marginTop: 4
        }
      }, d.key === "happiness" ? "Gratitude / Mindfulness" : d.key === "stress" ? "จัดการความเครียด / EAP" : d.key === "selfmgmt" ? "EQ Training / Coaching" : d.key === "empathy" ? "กิจกรรมอาสา / Mentor" : "Work-Life Balance"));
    }), /*#__PURE__*/React.createElement("div", {
      style: {
        flex: 1,
        minWidth: 140,
        background: "#F0FDF4",
        borderRadius: 10,
        padding: "12px 14px",
        borderLeft: "3px solid #10B981"
      }
    }, /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 10,
        fontWeight: 700,
        color: "#10B981"
      }
    }, "\u0E15\u0E34\u0E14\u0E15\u0E32\u0E21 \uD83D\uDFE2"), /*#__PURE__*/React.createElement("div", {
      style: {
        fontSize: 11,
        color: "#374151",
        marginTop: 4
      }
    }, "\u0E1B\u0E23\u0E30\u0E40\u0E21\u0E34\u0E19\u0E0B\u0E49\u0E33\u0E17\u0E38\u0E01 3 \u0E40\u0E14\u0E37\u0E2D\u0E19")))))))));
  }
  window.__DASHBOARDS__ = window.__DASHBOARDS__ || {};
  window.__DASHBOARDS__["tmhi"] = TMHIDashboard;
})();