#!/usr/bin/env node
/**
 * Normalize raw dashboard .txt (React/JSX) → pre-compiled .js files.
 *
 * Outputs both:
 *   - dashboards/<key>.jsx  (cleaned source, human-readable)
 *   - dashboards/<key>.js   (Babel-transpiled, no JSX, ready for <script>)
 *
 * Pre-compiling avoids @babel/standalone + eval() in the browser,
 * which is blocked by the site's Content-Security-Policy.
 *
 * Usage:  node "idp-dashboard/build.js"
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const SRC_DIR = path.join(__dirname, 'src');
const OUT_DIR = path.join(__dirname, 'dashboards');
const ROOT_DIR = path.resolve(__dirname, '..');

const FILES = [
  { src: '✔ Environment dashboard.txt',  key: 'env',      title: '🌿 Environment',         component: 'EnvDashboard' },
  { src: '✔ Physical dashboard.txt',     key: 'physical', title: '💪 Physical',            component: 'PhysicalDashboard' },
  { src: '✔ Tmhi v2 dashboard.txt',      key: 'tmhi',     title: '🧠 TMHI v2 (Mental)',    component: 'TMHIDashboard' },
  { src: '✔ UCLA dashboard_.txt',        key: 'ucla',     title: '🤝 UCLA (Social)',       component: 'UCLADashboard' },
  { src: '✔ Executive summary_.txt',     key: 'exec',     title: '📊 Executive Summary',   component: 'ExecutiveSummary' },
];

// ── Ensure Babel is available (install locally without touching package.json) ──
function ensureBabel() {
  try {
    require.resolve('@babel/core', { paths: [ROOT_DIR] });
    require.resolve('@babel/preset-react', { paths: [ROOT_DIR] });
  } catch {
    console.log('⟳ installing @babel/core + @babel/preset-react (no-save)…');
    execSync('npm install --no-save --silent @babel/core @babel/preset-react', {
      cwd: ROOT_DIR, stdio: 'inherit'
    });
  }
}
ensureBabel();
const babel = require(require.resolve('@babel/core', { paths: [ROOT_DIR] }));

// ── Source normalization ──────────────────────────────────────────────────────
function normalize(src) {
  return src
    .replace(/[\u201C\u201D\u201F\u2033]/g, '"')
    .replace(/[\u2018\u2019\u201B\u2032]/g, "'")
    .replace(/\u2026/g, '...')
    .split(/\r?\n/)
    .filter(line => !/^\s*```\w*\s*$/.test(line))
    .join('\n');
}

function stripImports(src) {
  src = src.replace(/^\s*import\s+\{[^}]*\}\s+from\s+["']react["'];?\s*$/m, '');
  src = src.replace(/import\s*\{[\s\S]*?\}\s*from\s*["']recharts["'];?/g, '');
  return src;
}

function rewriteExport(src, componentName) {
  return src.replace(
    new RegExp(`export\\s+default\\s+function\\s+${componentName}\\s*\\(`),
    `function ${componentName}(`
  );
}

const HEADER = (component) => `/* auto-generated by build.js – do not edit */
(function () {
  'use strict';
  var React = window.React;
  var Recharts = window.Recharts;
  var useState = React.useState, useMemo = React.useMemo, useEffect = React.useEffect, useRef = React.useRef, Fragment = React.Fragment;
  var BarChart = Recharts.BarChart, Bar = Recharts.Bar, XAxis = Recharts.XAxis, YAxis = Recharts.YAxis,
      CartesianGrid = Recharts.CartesianGrid, Tooltip = Recharts.Tooltip, ResponsiveContainer = Recharts.ResponsiveContainer,
      RadarChart = Recharts.RadarChart, Radar = Recharts.Radar, PolarGrid = Recharts.PolarGrid,
      PolarAngleAxis = Recharts.PolarAngleAxis, PolarRadiusAxis = Recharts.PolarRadiusAxis,
      LineChart = Recharts.LineChart, Line = Recharts.Line, AreaChart = Recharts.AreaChart, Area = Recharts.Area,
      PieChart = Recharts.PieChart, Pie = Recharts.Pie, Cell = Recharts.Cell,
      ScatterChart = Recharts.ScatterChart, Scatter = Recharts.Scatter, ZAxis = Recharts.ZAxis,
      ComposedChart = Recharts.ComposedChart, Legend = Recharts.Legend, ReferenceLine = Recharts.ReferenceLine;

`;

const FOOTER = (key, component) => `

  window.__DASHBOARDS__ = window.__DASHBOARDS__ || {};
  window.__DASHBOARDS__[${JSON.stringify(key)}] = ${component};
})();
`;

// Header/footer for the human-readable .jsx output (kept for reference)
const JSX_HEADER = `/* auto-generated by build.js – do not edit */
const { useState, useMemo, useEffect, useRef, Fragment } = React;
const {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis,
  LineChart, Line, AreaChart, Area, PieChart, Pie, Cell,
  ScatterChart, Scatter, ZAxis, ComposedChart, Legend, ReferenceLine
} = Recharts;

`;
const JSX_FOOTER = (key, component) => `
window.__DASHBOARDS__ = window.__DASHBOARDS__ || {};
window.__DASHBOARDS__[${JSON.stringify(key)}] = ${component};
`;

fs.mkdirSync(OUT_DIR, { recursive: true });

for (const f of FILES) {
  const raw = fs.readFileSync(path.join(SRC_DIR, f.src), 'utf8');
  let code = normalize(raw);
  code = stripImports(code);
  code = rewriteExport(code, f.component);

  // (1) Keep human-readable .jsx for debugging
  fs.writeFileSync(
    path.join(OUT_DIR, f.key + '.jsx'),
    JSX_HEADER + code + JSX_FOOTER(f.key, f.component),
    'utf8'
  );

  // (2) Pre-compiled .js (no JSX, no eval at runtime)
  const compileInput = HEADER(f.component) + code + FOOTER(f.key, f.component);
  const { code: compiled } = babel.transformSync(compileInput, {
    presets: [['@babel/preset-react', { runtime: 'classic' }]],
    filename: f.key + '.js',
    babelrc: false,
    configFile: false,
  });
  fs.writeFileSync(path.join(OUT_DIR, f.key + '.js'), compiled, 'utf8');

  console.log('✔', f.key, '→', f.key + '.js (' + Math.round(compiled.length / 1024) + ' KB)');
}

const manifest = JSON.stringify(
  FILES.map(f => ({ key: f.key, title: f.title, file: f.key + '.js' })), null, 2
);
fs.writeFileSync(path.join(OUT_DIR, 'manifest.json'), manifest);
console.log('✔ manifest.json');
