-- =============================================
-- Migration: Drop legacy CH1 turnover/transfer summary columns
-- Date: 2026-04-06
-- Purpose:
-- - Remove columns no longer used by the current CH1 form
-- - Keep the current 5-year staff movement model intact
-- - Handle ch1_google_sync_queue view dependency safely
-- =============================================

-- Step 1: Replace view to exclude legacy columns before dropping them
DROP VIEW IF EXISTS public.ch1_google_sync_queue;

CREATE OR REPLACE VIEW public.ch1_google_sync_queue AS
SELECT 
  id,
  created_at,
  updated_at,
  submitted_at,
  organization,
  org_code,
  strategic_overview,
  org_structure,
  total_staff,
  type_official,
  type_employee,
  type_contract,
  type_other,
  age_u30,
  age_31_40,
  age_41_50,
  age_51_60,
  service_u1,
  service_1_5,
  service_6_10,
  service_11_15,
  service_16_20,
  service_21_25,
  service_26_30,
  service_over30,
  pos_o1,
  pos_o2,
  pos_o3,
  pos_o4,
  pos_k1,
  pos_k2,
  pos_k3,
  pos_k4,
  pos_k5,
  pos_m1,
  pos_m2,
  pos_s1,
  pos_s2,
  begin_2564,
  begin_2565,
  begin_2566,
  begin_2567,
  begin_2568,
  end_2564,
  end_2565,
  end_2566,
  end_2567,
  end_2568,
  leave_2564,
  leave_2565,
  leave_2566,
  leave_2567,
  leave_2568,
  rate_2564,
  rate_2565,
  rate_2566,
  rate_2567,
  rate_2568,
  related_policies,
  context_challenges,
  disease_diabetes,
  disease_hypertension,
  disease_cardiovascular,
  disease_kidney,
  disease_liver,
  disease_cancer,
  disease_obesity,
  disease_other_count,
  disease_other_detail,
  disease_report_type,
  ncd_count,
  ncd_ratio_pct,
  sick_leave_days,
  sick_leave_avg,
  sick_leave_report_type,
  clinic_report_type,
  clinic_users_per_year,
  clinic_top_symptoms,
  clinic_top_medications,
  mental_stress,
  mental_anxiety,
  mental_sleep,
  mental_burnout,
  mental_depression,
  mental_health_report_type,
  engagement_score_2564,
  engagement_score_2565,
  engagement_score_2566,
  engagement_score_2567,
  engagement_score_2568,
  engagement_low_areas,
  other_wellbeing_surveys,
  mentoring_system,
  job_rotation,
  idp_system,
  career_path_system,
  training_hours,
  digital_systems,
  ergonomics_status,
  ergonomics_detail,
  ergonomics_planned_detail,
  ergonomics_in_progress_detail,
  ergonomics_done_detail,
  strategic_priority_rank1,
  strategic_priority_rank2,
  strategic_priority_rank3,
  google_sync_status,
  google_sync_attempts,
  google_sync_error,
  google_sync_requested_at,
  google_synced_at,
  google_sheet_row_number,
  google_drive_sync_status,
  google_drive_synced_at,
  google_drive_error,
  google_drive_files,
  is_test,
  submission_mode,
  test_run_id,
  form_version,
  respondent_email,
  status
FROM public.hrd_ch1_responses
WHERE submitted_at IS NOT NULL
  AND (
    google_sync_status IN ('pending', 'failed')
    OR google_drive_sync_status IN ('pending', 'failed')
  );

-- Step 2: Now safely drop the legacy columns
ALTER TABLE public.hrd_ch1_responses
  DROP COLUMN IF EXISTS turnover_count,
  DROP COLUMN IF EXISTS turnover_rate,
  DROP COLUMN IF EXISTS transfer_count,
  DROP COLUMN IF EXISTS transfer_rate;

COMMENT ON TABLE public.hrd_ch1_responses IS 'CH1 responses schema cleaned on 2026-04-06 to remove legacy turnover/transfer summary columns; use yearly fields begin_2564-2568, end_2564-2568, leave_2564-2568, rate_2564-2568 instead.';
